package com.rentit.sales.domain.model;


public enum PurchaseOrderStatus {
    PENDING, PENDING_EXTENSION, OPEN, REJECTED, CLOSED, CREATED, CANCEL,CANCEL_PENDING, PENDING_WORKER_CONFIRM,CANCEL_REJECTED, EXPIRED
}
